export const BASE_IMAGE_URL = "https://utfs.io/f";

export const provincesOfIndonesia = [
  "Aceh",
  "North Sumatra",
  "West Sumatra",
  "Riau",
  "Jambi",
  "South Sumatra",
  "Bengkulu",
  "Lampung",
  "Bangka Belitung",
  "Riau Islands",
  "Jakarta",
  "West Java",
  "Central Java",
  "East Java",
  "Banten",
  "Bali",
  "West Nusa Tenggara",
  "East Nusa Tenggara",
  "West Kalimantan",
  "Central Kalimantan",
  "South Kalimantan",
  "East Kalimantan",
  "North Kalimantan",
  "North Sulawesi",
  "Gorontalo",
  "West Sulawesi",
  "Central Sulawesi",
  "South Sulawesi",
  "Southeast Sulawesi",
  "Maluku",
  "North Maluku",
  "Papua",
  "West Papua",
];
